config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # get "/tasks", to: "tasks#index"
  # get "/tasks/new", to: "tasks#new", as: :new_task
  # get "/tasks/:id", to: "tasks#show", as: :task
  # post "/tasks", to: "tasks#create"
  # get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  # patch "tasks/:id", to: "tasks#update"
  # delete "/tasks/:id", to: "tasks#destroy", as: :d_task
  resources :tasks

  # delete "tasks/:id", to: "tasks#destroy"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
@tasks = Task.all
  end
  def show

  end
  def new
    @task = Task.new
  end
  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_path, notice: 'Task was successfully created.'
    else
      render :new
    end
  end
  def edit

  end
  def update

    if @task.update(task_params)
      redirect_to tasks_path(@task), notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end
  def destroy
 
    @task.destroy
    # No need for app/views/tasks/destroy.html.erb
    redirect_to tasks_path, status: :see_other
  end

  private

    def task_params
      params.require(:task).permit(:title, :details, :completed)
    end
    def set_task
      @task = Task.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container"> <%= yield %>
    </div>

  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1> Edit This Task <%= @task.title %> </h1>

<%= render "form", task: @task %>

app/views/tasks/index.html.erb
  <h1>welcome to Anouar's Tasks list</h1>

<ul>
  <% @tasks.each do |task| %>
    <li><%= link_to task.title, task_path(task) %></li>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<h1>add new task</h1>
<!-- app/views/tasks/new.html.erb -->

<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<h1>details of Anouar's my Tasks</h1>

<p>Title : <%= @task.title %></p>
<p>Details: <%= @task. details %></p>

<h1> Edit This Task <%= @task.title %> </h1>

<%= link_to "edit", edit_task_path %>

<%= link_to "Delete",
  task_path(@task),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>